### ISSUE TITLE
Code is slow to run at first

### ISSUE THREAD

**Issue by phajy** [astro-group-bristol/DiscJetConnections.jl#4]
When we first run the code to produce a plot (e.g., plotTest.jl) it take a while to run because it needs to precompile DiscJetConnections and Plots in particular. I'm not sure if there is some way to speed this up, or are Plots not being cached because of a warning about some module being missing from the cache?

```
julia> using DiscJetConnections
[ Info: Precompiling DiscJetConnections [9ec08b66-6ee8-447e-945d-4d196407106a]
┌ Warning: The call to compilecache failed to create a usable precompiled cache file for Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
│   exception = Required dependency FFMPEG_jll [b22a6f82-2f65-5046-a5b2-351ab43fb4e5] failed to load from a cache file.
└ @ Base loading.jl:1055
...
```

**Comment by fjebaker** [comment]
Have you tried updating your development environment?
```julia
Pkg> up
```

Else I would try removing and re-adding Plots:
```julia
Pkg> remove Plots
Pkg> add Plots
```

Hopefully one of those things will cause Julia to realise it's missing a dependency and re-download it.

**Comment by phajy** [comment]
Thanks! That did the trick - much faster now and no problems with the dependencies. I just needed to use `up`; no need to re-add `Plots`.

**Comment by fjebaker** [comment]
Excellent! I'll close the issue then :)
